"""
M5 QA Engine — Citation Builder.

WHAT: Builds citation lists from retrieved chunks, deduplicates by source,
      filters to only referenced citations, and formats them for display.

WHY: Every M5 answer must have traceable source citations so engineers
     can verify the regulatory basis of each answer. The format is:
     regulation -> section -> clause -> excerpt.
"""

from contracts.qa_engine import Citation
from contracts.retrieval import ScoredChunk


def build_citations(chunks: list[ScoredChunk]) -> list[Citation]:
    """
    WHAT: Build citation list from retrieved chunks.
          Extracts source metadata from each chunk, deduplicates by
          (source_doc, section), and assigns index numbers.

    WHY: Each retrieved chunk may come from the same source document
         and section. Deduplication prevents duplicate citations in the
         answer while preserving the order of first occurrence.

    Args:
        chunks: List of ScoredChunk objects from the retrieval pipeline.

    Returns:
        List of unique Citation objects with sequential 1-based indices.
    """
    seen: set[tuple[str, str]] = set()
    citations: list[Citation] = []
    for sc in chunks:
        meta = sc.chunk.metadata
        # Dedup key: (source_filename, regulation_name)
        key = (meta.source_filename, meta.regulation_name or "")
        if key not in seen:
            seen.add(key)
            citations.append(Citation(
                index=len(citations) + 1,
                source_doc=meta.source_filename,
                section=meta.regulation_name or "",
                clause_id=meta.chapter_section,
                excerpt=sc.chunk.text[:200] if sc.chunk.text else "",
            ))
    return citations


def attach_citations(answer: str, citations: list[Citation]) -> list[Citation]:
    """
    WHAT: Filter citations to only those referenced in the answer via
          [1] [2] markers. Returns the subset of citations actually used.

    WHY: The LLM may reference only a subset of the retrieved citations
         in its answer. We should only display the citations that are
         actually cited in the answer text.

    Args:
        answer: The answer text generated by the LLM, expected to contain
                citation markers like [1], [2], etc.
        citations: The full list of Citation objects.

    Returns:
        Filtered list containing only citations whose index markers
        appear in the answer text.
    """
    used_indices: set[int] = set()
    for c in citations:
        if f"[{c.index}]" in answer:
            used_indices.add(c.index)
    return [c for c in citations if c.index in used_indices]


def format_citation_text(citations: list[Citation]) -> str:
    """
    WHAT: Format citations as human-readable text for appending to answers.

    WHY: Citations need to be presented in a structured, readable format
         at the end of each answer, with clear source identification
         and excerpt previews.

    Args:
        citations: List of Citation objects to format.

    Returns:
        A markdown-formatted string with ## Sources header and numbered
        citation entries.
    """
    lines = ["\n## Sources"]
    for c in citations:
        line = f"[{c.index}] {c.source_doc}, {c.section} — {c.excerpt[:80]}..."
        if c.clause_id:
            line += f" ({c.clause_id})"
        lines.append(line)
    return "\n".join(lines)
